env:
  project: GCLOUD_PROJECT
  bucket: BUCKET
  blobdir: BLOBDIR
  dataset: DATASET

api:
  base: https://fantasy.premierleague.com/api
  endpoints:
    boostrap_static:
      name: bootstrap-static
      description: "This endpoint returns general information about the FPL game"

      # default params
      default_table_config:
        refresh_params:
          frequency: daily # default frequency
          write_disposition: overwrite
        ingest: True
        file_type: json # cloud storage file type
        schema: autodetect
        tags:
          - bootstrap-static

      tables:
        # tables from bootstrap-static
        events:
          description: >
            (grain: gameweek, current season only) basic information of every Gameweek such as
            average score, highest score, top scoring player, most captained, etc.

        game_settings:
          description: >
            (grain: 1 row) global settings for the game such as squad_squadplay and squad_squadsize.
            These settings are important for defining ML apps but not required in the analytics warehouse
          config:
            ingest: False

        phases:
          description: >
            (grain: 1 row per month + overall, current season only) start, stop and 
            highest score events
          config:
            ingest: False

        teams:
          description: >
            (grain: 1 row per team, current season only) basic information of current
            Premier League clubs.

        total_players:
          description: >
            (grain: 1 row, current season only) total FPL players
          config:
            ingest: False

        elements:
          description: >
            (grain: 1 row per player, current season only) current information of all
            Premier League players including points, status, value, match stats (goals, assists, etc.),
            ICT index, etc

        element_types:
          description: >
            (grain: 1 row per position) basic information about players position (GK, DEF, MID, FWD)